package com.hotel.service.impl;
import com.hotel.dao.FrontDeskDao;import com.hotel.dto.*;import com.hotel.exception.BusinessException;import org.junit.jupiter.api.*;import java.math.BigDecimal;import java.sql.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class FrontDeskServiceImplTest{
 FrontDeskDao dao;Connection c;FrontDeskServiceImpl service;
 @BeforeEach void setUp()throws Exception{dao=mock(FrontDeskDao.class);c=mock(Connection.class);when(c.getAutoCommit()).thenReturn(true);when(c.getTransactionIsolation()).thenReturn(Connection.TRANSACTION_READ_COMMITTED);service=new FrontDeskServiceImpl(dao,()->c);}
 CheckInDto booking(String status,boolean holder,boolean primary,boolean doc,String need,String paid,List<RoomSelectionDto> selections,int existing){return new CheckInDto(20,"BK-20",status,2,"Nguyễn Văn A",holder,LocalDate.now(),LocalDate.now().plusDays(2),primary,doc,new BigDecimal(need),new BigDecimal(paid),List.of(new StayingGuestDto(1,"Nguyễn Văn A",null,"CCCD","123","VN",true)),selections,existing);}
 RoomSelectionDto rr(long id,long type,int qty){return new RoomSelectionDto(id,type,"Deluxe",qty,List.of());}RoomStateDto ready(long id,long type){return new RoomStateDto(id,type,"R"+id,1,"AVAILABLE","INSPECTED",true,false);}
 @Test void oneRoomCheckInIsAtomic()throws Exception{when(dao.findCheckIn(c,"20",true)).thenReturn(Optional.of(booking("CONFIRMED",true,true,true,"100","100",List.of(rr(10,30,1)),0)));when(dao.findRoomState(c,40,true)).thenReturn(Optional.of(ready(40,30)));when(dao.updateRoomStatus(c,40,"OCCUPIED","INSPECTED")).thenReturn(1);when(dao.markCheckedIn(c,20,7)).thenReturn(1);service.checkIn(20,Map.of(10L,List.of(40L)),true,7);verify(dao).insertAssignment(c,10,40,7);verify(dao).ensureDraftInvoice(c,20);verify(c).commit();}
 @Test void multipleRoomTypesLinkToCorrectReservationRows()throws Exception{var rows=List.of(rr(10,30,2),rr(11,31,1));when(dao.findCheckIn(c,"20",true)).thenReturn(Optional.of(booking("CONFIRMED",true,true,true,"0","0",rows,0)));when(dao.findRoomState(c,40,true)).thenReturn(Optional.of(ready(40,30)));when(dao.findRoomState(c,41,true)).thenReturn(Optional.of(ready(41,30)));when(dao.findRoomState(c,50,true)).thenReturn(Optional.of(ready(50,31)));when(dao.updateRoomStatus(eq(c),anyLong(),eq("OCCUPIED"),eq("INSPECTED"))).thenReturn(1);when(dao.markCheckedIn(c,20,7)).thenReturn(1);service.checkIn(20,Map.of(10L,List.of(40L,41L),11L,List.of(50L)),true,7);verify(dao).insertAssignment(c,10,40,7);verify(dao).insertAssignment(c,10,41,7);verify(dao).insertAssignment(c,11,50,7);}
 @Test void rejectsMissingDocumentConfirmation() {assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(),false,7));}
 @Test void rejectsDepositAndPrimaryDocument()throws Exception{when(dao.findCheckIn(c,"20",true)).thenReturn(Optional.of(booking("CONFIRMED",true,true,false,"0","0",List.of(rr(10,30,1)),0)));assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(10L,List.of(40L)),true,7));when(dao.findCheckIn(c,"20",true)).thenReturn(Optional.of(booking("CONFIRMED",true,true,true,"100","99",List.of(rr(10,30,1)),0)));assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(10L,List.of(40L)),true,7));}
 @Test void rejectsMissingDuplicateAndWrongTypeSelections()throws Exception{when(dao.findCheckIn(c,"20",true)).thenReturn(Optional.of(booking("CONFIRMED",true,true,true,"0","0",List.of(rr(10,30,2)),0)));assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(10L,List.of(40L)),true,7));assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(10L,List.of(40L,40L)),true,7));when(dao.findRoomState(c,40,true)).thenReturn(Optional.of(ready(40,99)));assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(10L,List.of(40L,41L)),true,7));}
 @Test void rejectsCleanButNotInspected()throws Exception{when(dao.findCheckIn(c,"20",true)).thenReturn(Optional.of(booking("CONFIRMED",true,true,true,"0","0",List.of(rr(10,30,1)),0)));when(dao.findRoomState(c,40,true)).thenReturn(Optional.of(new RoomStateDto(40,30,"101",1,"AVAILABLE","CLEAN",true,false)));assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(10L,List.of(40L)),true,7));verify(c).rollback();}
 @Test void rejectsPreAssignmentAndRepeatCheckIn()throws Exception{when(dao.findCheckIn(c,"20",true)).thenReturn(Optional.of(booking("CONFIRMED",true,true,true,"0","0",List.of(rr(10,30,1)),1)));assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(10L,List.of(40L)),true,7));when(dao.findCheckIn(c,"20",true)).thenReturn(Optional.of(booking("CHECKED_IN",true,true,true,"0","0",List.of(rr(10,30,1)),0)));assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(10L,List.of(40L)),true,7));}
 @Test void concurrencyConflictRollsEverythingBack()throws Exception{when(dao.findCheckIn(c,"20",true)).thenReturn(Optional.of(booking("CONFIRMED",true,true,true,"0","0",List.of(rr(10,30,1)),0)));when(dao.findRoomState(c,40,true)).thenReturn(Optional.of(ready(40,30)));doThrow(new SQLException("unique","23000",2601)).when(dao).insertAssignment(c,10,40,7);BusinessException e=assertThrows(BusinessException.class,()->service.checkIn(20,Map.of(10L,List.of(40L)),true,7));assertTrue(e.getMessage().contains("no longer available"));verify(c).rollback();verify(dao,never()).ensureDraftInvoice(any(),anyLong());}
 @Test void changeRoomPreservesHistory()throws Exception{var old=new RoomChangeDto(5,20,10,"BK-20","Nguyễn Văn A","CHECKED_IN",LocalDate.now(),LocalDate.now().plusDays(1),30,"Deluxe",40,"101",1,LocalDateTime.now());when(dao.findRoomChange(c,5,true)).thenReturn(Optional.of(old));when(dao.findRoomState(c,41,true)).thenReturn(Optional.of(ready(41,30)));when(dao.closeAssignment(c,5,"Noise")).thenReturn(1);when(dao.updateRoomStatus(c,40,"AVAILABLE","DIRTY")).thenReturn(1);when(dao.updateRoomStatus(c,41,"OCCUPIED","INSPECTED")).thenReturn(1);service.changeRoom(5,41,"Noise",7);verify(dao).closeAssignment(c,5,"Noise");verify(dao).insertAssignment(c,10,41,7);verify(c).commit();}
 @Test void changeRejectsUninspectedAndBlankReason()throws Exception{assertThrows(BusinessException.class,()->service.changeRoom(5,41," ",7));var old=new RoomChangeDto(5,20,10,"BK-20","Holder","CHECKED_IN",LocalDate.now(),LocalDate.now().plusDays(1),30,"Deluxe",40,"101",1,LocalDateTime.now());when(dao.findRoomChange(c,5,true)).thenReturn(Optional.of(old));when(dao.findRoomState(c,41,true)).thenReturn(Optional.of(new RoomStateDto(41,30,"102",1,"AVAILABLE","CLEAN",true,false)));assertThrows(BusinessException.class,()->service.changeRoom(5,41,"Reason",7));}
}
