package com.hotel.controller;

import com.hotel.dao.impl.FrontDeskDaoImpl; import com.hotel.dto.SessionUser; import com.hotel.exception.*; import com.hotel.service.FrontDeskService; import com.hotel.service.impl.FrontDeskServiceImpl; import com.hotel.util.DBConnection;
import jakarta.servlet.*; import jakarta.servlet.annotation.WebServlet; import jakarta.servlet.http.*; import java.io.IOException;

@WebServlet("/receptionist/rooms/change") public class ChangeRoomServlet extends HttpServlet {private final FrontDeskService service=new FrontDeskServiceImpl(new FrontDeskDaoImpl(),DBConnection::getConnection);
 protected void doGet(HttpServletRequest q,HttpServletResponse s)throws ServletException,IOException{try{long id=Long.parseLong(q.getParameter("assignmentId"));var d=service.changeDetails(id);if(d.isEmpty()){s.sendError(404);return;}q.setAttribute("details",d.get());q.setAttribute("rooms",service.changeCandidates(id));flash(q);q.getRequestDispatcher("/WEB-INF/views/receptionist/rooms/change.jsp").forward(q,s);}catch(NumberFormatException e){s.sendError(400,"Assignment ID không hợp lệ.");}catch(DataAccessException e){getServletContext().log("Change-room page failed",e);s.sendError(500);}}
 protected void doPost(HttpServletRequest q,HttpServletResponse s)throws IOException{String id=q.getParameter("assignmentId");try{long a=Long.parseLong(id),room=Long.parseLong(q.getParameter("newRoomId"));SessionUser u=(SessionUser)q.getSession().getAttribute("sessionUser");service.changeRoom(a,room,q.getParameter("reason"),u.userId());q.getSession().setAttribute("flashSuccess","Đổi phòng thành công; phòng cũ đã chuyển sang trạng thái cần dọn.");s.sendRedirect(q.getContextPath()+"/receptionist/assignments/history?keyword="+java.net.URLEncoder.encode(q.getParameter("bookingCode"),java.nio.charset.StandardCharsets.UTF_8));}catch(NumberFormatException|BusinessException e){q.getSession().setAttribute("flashError",e instanceof BusinessException?e.getMessage():"Dữ liệu đổi phòng không hợp lệ.");s.sendRedirect(q.getContextPath()+"/receptionist/rooms/change?assignmentId="+(id!=null&&id.matches("[0-9]+")?id:"0"));}catch(DataAccessException e){getServletContext().log("Change room failed",e);s.sendError(500);}}
 private void flash(HttpServletRequest q){for(String k:new String[]{"flashSuccess","flashError"}){Object x=q.getSession().getAttribute(k);if(x!=null){q.setAttribute(k.equals("flashSuccess")?"success":"error",x);q.getSession().removeAttribute(k);}}}
}
