package com.hotel.dao.impl;
import com.hotel.dao.CustomerDao; import com.hotel.dto.*; import com.hotel.exception.DataAccessException; import com.hotel.util.DBConnection; import java.sql.*; import java.util.*;
public class CustomerDaoImpl implements CustomerDao {
 private static String like(String s){return "%"+s.replace("[","[[]").replace("%","[%]").replace("_","[_]")+"%";}
 public PageResult<CustomerSummaryDto> search(CustomerSearchCriteria x){String where=" WHERE (? IS NULL OR status_code=?) AND (? IS NULL OR LOWER(full_name) LIKE LOWER(?) OR LOWER(COALESCE(phone,'')) LIKE LOWER(?) OR LOWER(COALESCE(email,'')) LIKE LOWER(?) OR LOWER(COALESCE(id_document_number,'')) LIKE LOWER(?) OR LOWER(customer_code) LIKE LOWER(?))";String count="SELECT COUNT(*) FROM customers"+where;String query="SELECT customer_id,customer_code,full_name,phone,email,id_document_number,status_code FROM customers"+where+" ORDER BY updated_at DESC,customer_id DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY";String k=x.keyword()==null||x.keyword().isBlank()?null:like(x.keyword());try(Connection c=DBConnection.getConnection()){long total;try(PreparedStatement p=c.prepareStatement(count)){bind(p,x.status(),k);try(ResultSet r=p.executeQuery()){r.next();total=r.getLong(1);}}List<CustomerSummaryDto> out=new ArrayList<>();try(PreparedStatement p=c.prepareStatement(query)){int i=bind(p,x.status(),k);p.setInt(i++,(x.page()-1)*x.pageSize());p.setInt(i,x.pageSize());try(ResultSet r=p.executeQuery()){while(r.next())out.add(new CustomerSummaryDto(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7)));}}return new PageResult<>(out,x.page(),x.pageSize(),total);}catch(SQLException e){throw new DataAccessException("Unable to search customers",e);}}
 private int bind(PreparedStatement p,String status,String k)throws SQLException{int i=1;p.setString(i++,status);p.setString(i++,status);p.setString(i++,k);for(int n=0;n<5;n++)p.setString(i++,k);return i;}
 public Optional<CustomerDetailDto> findDetail(long id){String q="SELECT customer_id,customer_code,full_name,email,phone,date_of_birth,id_document_type,id_document_number,nationality,[address],status_code,created_at,updated_at FROM customers WHERE customer_id=?";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setLong(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())return Optional.empty();return Optional.of(new CustomerDetailDto(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getObject(6,java.time.LocalDate.class),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11),r.getObject(12,java.time.LocalDateTime.class),r.getObject(13,java.time.LocalDateTime.class),reservations(c,id),stays(c,id)));}}catch(SQLException e){throw new DataAccessException("Unable to load customer",e);}}
 private List<ReservationHistoryDto> reservations(Connection c,long id)throws SQLException{List<ReservationHistoryDto> a=new ArrayList<>();try(PreparedStatement p=c.prepareStatement("SELECT booking_code,check_in_date,check_out_date,status_code,adult_count,child_count,total_amount,booked_at FROM reservations WHERE customer_id=? ORDER BY booked_at DESC")){p.setLong(1,id);try(ResultSet r=p.executeQuery()){while(r.next())a.add(new ReservationHistoryDto(r.getString(1),r.getObject(2,java.time.LocalDate.class),r.getObject(3,java.time.LocalDate.class),r.getString(4),r.getInt(5),r.getInt(6),r.getBigDecimal(7),r.getObject(8,java.time.LocalDateTime.class)));}}return a;}
 private List<StayHistoryDto> stays(Connection c,long id)throws SQLException{List<StayHistoryDto>a=new ArrayList<>();String q="SELECT v.booking_code,v.actual_check_in_at,v.actual_check_out_at,rm.room_number,rt.type_name,ra.assigned_at,ra.unassigned_at,ra.is_current FROM reservations v JOIN reservation_rooms rr ON rr.reservation_id=v.reservation_id JOIN room_types rt ON rt.room_type_id=rr.room_type_id JOIN room_assignments ra ON ra.reservation_room_id=rr.reservation_room_id JOIN rooms rm ON rm.room_id=ra.room_id WHERE v.customer_id=? AND v.status_code IN ('CHECKED_IN','CHECKED_OUT') ORDER BY ra.assigned_at DESC";try(PreparedStatement p=c.prepareStatement(q)){p.setLong(1,id);try(ResultSet r=p.executeQuery()){while(r.next())a.add(new StayHistoryDto(r.getString(1),r.getObject(2,java.time.LocalDateTime.class),r.getObject(3,java.time.LocalDateTime.class),r.getString(4),r.getString(5),r.getObject(6,java.time.LocalDateTime.class),r.getObject(7,java.time.LocalDateTime.class),r.getBoolean(8)));}}return a;}
 public boolean documentExists(String t,String n,Long ex){if(t==null||n==null)return false;String q="SELECT 1 FROM customers WHERE id_document_type=? AND id_document_number=? AND (? IS NULL OR customer_id<>?)";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,t);p.setString(2,n);if(ex==null){p.setNull(3,Types.BIGINT);p.setNull(4,Types.BIGINT);}else{p.setLong(3,ex);p.setLong(4,ex);}try(ResultSet r=p.executeQuery()){return r.next();}}catch(SQLException e){throw new DataAccessException("Unable to validate document",e);}}
 public long create(CustomerFormDto f,long creator,String code){String q="INSERT INTO customers(user_id,created_by_user_id,customer_code,full_name,email,phone,date_of_birth,id_document_type,id_document_number,nationality,[address],status_code) VALUES(NULL,?,?,?,?,?,?,?,?,?,?,'ACTIVE')";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){p.setLong(1,creator);p.setString(2,code);fields(p,f,3);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())return r.getLong(1);throw new SQLException("No generated key");}}catch(SQLException e){throw new DataAccessException("Unable to create customer",e);}}
 public boolean update(CustomerFormDto f){String q="UPDATE customers SET full_name=?,email=?,phone=?,date_of_birth=?,id_document_type=?,id_document_number=?,nationality=?,[address]=?,updated_at=SYSUTCDATETIME() WHERE customer_id=? AND updated_at=?";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){fields(p,f,1);p.setLong(9,f.id());p.setTimestamp(10,Timestamp.valueOf(f.version()));return p.executeUpdate()==1;}catch(SQLException e){throw new DataAccessException("Unable to update customer",e);}}
 private void fields(PreparedStatement p,CustomerFormDto f,int i)throws SQLException{p.setString(i++,f.fullName());p.setString(i++,f.email());p.setString(i++,f.phone());if(f.dateOfBirth()==null)p.setNull(i++,Types.DATE);else p.setDate(i++,java.sql.Date.valueOf(f.dateOfBirth()));p.setString(i++,f.idDocumentType());p.setString(i++,f.idDocumentNumber());p.setString(i++,f.nationality());p.setString(i,f.address());}
}
