package com.hotel.service.impl;
import com.hotel.dao.FrontDeskDao;import com.hotel.dto.*;import com.hotel.exception.*;import com.hotel.service.FrontDeskService;import com.hotel.util.ConnectionProvider;import java.sql.*;import java.util.*;
public class FrontDeskServiceImpl implements FrontDeskService{
 private final FrontDeskDao dao;private final ConnectionProvider connections;public FrontDeskServiceImpl(FrontDeskDao d,ConnectionProvider c){dao=d;connections=c;}
 public Optional<AssignRoomPageDto> assignmentPage(long id){if(id<=0)return Optional.empty();try(Connection c=connections.getConnection()){var t=dao.findAssignmentTarget(c,id,false);return t.map(v->{try{return new AssignRoomPageDto(v,dao.findAvailableRooms(c,id));}catch(SQLException e){throw data("Unable to load room selection",e);}});}catch(SQLException e){throw data("Unable to load room selection",e);}}
 public Optional<CheckInDto> checkInDetails(String id){String x=clean(id);if(x==null)return Optional.empty();try(Connection c=connections.getConnection()){return dao.findCheckIn(c,x,false);}catch(SQLException e){throw data("Unable to load check-in",e);}}
 public List<ReservationSearchDto> searchReservations(String keyword){String x=keyword==null?null:keyword.trim();if(x==null||x.isEmpty())return List.of();if(x.length()>100)x=x.substring(0,100);try(Connection c=connections.getConnection()){return dao.searchReservations(c,x);}catch(SQLException e){throw data("Unable to search reservations",e);}}
 public void checkIn(long id,Map<Long,List<Long>> selected,boolean documentsChecked,long user)throws BusinessException{if(id<=0||user<=0)throw new BusinessException("Dữ liệu check-in không hợp lệ.");if(!documentsChecked)throw new BusinessException("Receptionist phải xác nhận đã kiểm tra giấy tờ bản gốc.");Map<Long,List<Long>> input=selected==null?Map.of():selected;tx(c->{CheckInDto d=dao.findCheckIn(c,String.valueOf(id),true).orElseThrow(()->new BusinessException("Reservation không tồn tại."));if(!"CONFIRMED".equals(d.statusCode()))throw new BusinessException("Chỉ reservation CONFIRMED mới được check-in.");if(!d.bookingHolderActive())throw new BusinessException("Người đứng tên booking không còn ở trạng thái hợp lệ.");if(!d.primaryGuestPresent())throw new BusinessException("Booking chưa có primary guest.");if(!d.primaryGuestHasDocument())throw new BusinessException("Primary guest chưa có đầy đủ giấy tờ.");if(d.depositPaid().compareTo(d.depositRequired())<0)throw new BusinessException("Tiền đặt cọc chưa đạt yêu cầu.");if(d.existingAssignmentCount()!=0)throw new BusinessException("Booking đã có assignment trước check-in; cần xử lý dữ liệu bất thường trước.");Set<Long> expected=new HashSet<>();Set<Long> uniqueRooms=new HashSet<>();for(RoomSelectionDto rr:d.roomSelections()){expected.add(rr.reservationRoomId());List<Long> rooms=input.getOrDefault(rr.reservationRoomId(),List.of());if(rooms.size()!=rr.requiredQuantity())throw new BusinessException("Phải chọn đúng "+rr.requiredQuantity()+" phòng cho "+rr.roomTypeName()+".");for(Long roomId:rooms){if(roomId==null||roomId<=0||!uniqueRooms.add(roomId))throw new BusinessException("Không được chọn trùng phòng.");RoomStateDto room=dao.findRoomState(c,roomId,true).orElseThrow(()->new BusinessException("Phòng được chọn không tồn tại."));validateReady(room,rr.roomTypeId());}}if(!expected.equals(input.keySet()))throw new BusinessException("Room selection không thuộc đúng reservation.");for(RoomSelectionDto rr:d.roomSelections())for(long roomId:input.get(rr.reservationRoomId())){dao.insertAssignment(c,rr.reservationRoomId(),roomId,user);if(dao.updateRoomStatus(c,roomId,"OCCUPIED","INSPECTED")!=1)throw new BusinessException("Không thể cập nhật trạng thái phòng.");}if(dao.markCheckedIn(c,id,user)!=1)throw new BusinessException("Reservation vừa được thay đổi. Vui lòng tải lại.");dao.ensureDraftInvoice(c,id);return null;});}
 public Optional<RoomChangeDto> changeDetails(long id){if(id<=0)return Optional.empty();try(Connection c=connections.getConnection()){return dao.findRoomChange(c,id,false);}catch(SQLException e){throw data("Unable to load room change",e);}}
 public List<AvailableRoomDto> changeCandidates(long id){try(Connection c=connections.getConnection()){var d=dao.findRoomChange(c,id,false);return d.isEmpty()?List.of():dao.findAvailableRooms(c,d.get().reservationRoomId());}catch(SQLException e){throw data("Unable to load replacement rooms",e);}}
 public void changeRoom(long aid,long newRoom,String reason,long user)throws BusinessException{String why=reason==null?"":reason.trim();if(aid<=0||newRoom<=0||user<=0)throw new BusinessException("Dữ liệu đổi phòng không hợp lệ.");if(why.isEmpty())throw new BusinessException("Vui lòng nhập lý do đổi phòng.");if(why.length()>255)throw new BusinessException("Lý do không được vượt quá 255 ký tự.");tx(c->{RoomChangeDto old=dao.findRoomChange(c,aid,true).orElseThrow(()->new BusinessException("Assignment hiện tại không tồn tại."));if(!"CHECKED_IN".equals(old.reservationStatus()))throw new BusinessException("Chỉ booking CHECKED_IN mới được đổi phòng.");if(old.oldRoomId()==newRoom)throw new BusinessException("Phòng mới phải khác phòng hiện tại.");RoomStateDto room=dao.findRoomState(c,newRoom,true).orElseThrow(()->new BusinessException("Phòng mới không tồn tại."));validateReady(room,old.roomTypeId());if(dao.closeAssignment(c,aid,why)!=1)throw new BusinessException("Assignment vừa được thay đổi.");if(dao.updateRoomStatus(c,old.oldRoomId(),"AVAILABLE","DIRTY")!=1)throw new BusinessException("Không thể cập nhật phòng cũ.");dao.insertAssignment(c,old.reservationRoomId(),newRoom,user);if(dao.updateRoomStatus(c,newRoom,"OCCUPIED","INSPECTED")!=1)throw new BusinessException("Không thể cập nhật phòng mới.");return null;});}
 public List<AssignmentHistoryDto> history(String id){String x=id==null?null:id.trim();if(x!=null&&x.isEmpty())x=null;if(x!=null&&x.length()>100)x=x.substring(0,100);try(Connection c=connections.getConnection()){return dao.findHistory(c,x);}catch(SQLException e){throw data("Unable to load assignment history",e);}}
 private void validateReady(RoomStateDto r,long type)throws BusinessException{if(!r.active()||r.roomTypeId()!=type||!"AVAILABLE".equals(r.operationalStatus())||!"INSPECTED".equals(r.cleaningStatus())||r.currentlyAssigned())throw new BusinessException("The selected room is no longer available. Please choose another room.");}
 private String clean(String x){if(x==null||x.trim().isEmpty()||x.trim().length()>30)return null;return x.trim();}private DataAccessException data(String m,SQLException e){return new DataAccessException(m,e);}
 private <T>T tx(Work<T>w)throws BusinessException{try(Connection c=connections.getConnection()){boolean a=c.getAutoCommit();int i=c.getTransactionIsolation();try{c.setAutoCommit(false);c.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);T x=w.run(c);c.commit();return x;}catch(BusinessException e){rollback(c);throw e;}catch(SQLException e){rollback(c);if(e.getErrorCode()==2601||e.getErrorCode()==2627||e.getErrorCode()==1205)throw new BusinessException("The selected room is no longer available. Please choose another room.");throw data("Front-desk transaction failed",e);}finally{try{c.setTransactionIsolation(i);c.setAutoCommit(a);}catch(SQLException ignored){}}}catch(SQLException e){throw data("Unable to connect to database",e);}}
 private void rollback(Connection c){try{c.rollback();}catch(SQLException ignored){}}@FunctionalInterface private interface Work<T>{T run(Connection c)throws SQLException,BusinessException;}
}
