<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="activePage" value="customers"/><c:set var="moduleCode" value="UC25"/><c:set var="pageTitle" value="Thông tin khách hàng"/>
<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Chi tiết khách hàng — Grand Horizon</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/receptionist.css?v=20260814"></head><body><div class="app-shell">
<%@ include file="../fragments/sidebar.jspf" %><main class="main-panel"><%@ include file="../fragments/header.jspf" %><div class="content">
    <a class="back-link" href="${pageContext.request.contextPath}/receptionist/customers">← Quay lại danh sách</a><c:if test="${not empty flash}"><p class="alert success">✓ <c:out value="${flash}"/></p></c:if>
    <section class="profile-card"><div class="profile-avatar">${customer.fullName.substring(0,1)}</div><div class="profile-main"><p class="eyebrow">CUSTOMER PROFILE</p><h1><c:out value="${customer.fullName}"/></h1><div><span class="code"><c:out value="${customer.code}"/></span><span class="status ${customer.status=='ACTIVE'?'success':'muted'}"><c:out value="${customer.status}"/></span></div></div><a class="primary" href="${pageContext.request.contextPath}/receptionist/customers/edit?id=${customer.id}">✎ Chỉnh sửa</a></section>
    <div class="detail-grid"><section class="panel"><div class="panel-title"><div><h2>Thông tin cá nhân</h2><p>Thông tin liên hệ và nhận diện</p></div></div><dl class="info-list"><dt>Email</dt><dd><c:out value="${customer.email}"/></dd><dt>Điện thoại</dt><dd><c:out value="${customer.phone}"/></dd><dt>Ngày sinh</dt><dd>${customer.dateOfBirth}</dd><dt>Giấy tờ</dt><dd><c:out value="${customer.idType}"/> — <c:out value="${customer.idNumber}"/></dd><dt>Quốc tịch</dt><dd><c:out value="${customer.nationality}"/></dd><dt>Địa chỉ</dt><dd><c:out value="${customer.address}"/></dd><dt>Khởi tạo</dt><dd>${customer.createdAt}</dd><dt>Cập nhật</dt><dd>${customer.updatedAt}</dd></dl></section>
    <section class="panel summary-panel"><span class="summary-icon">▤</span><h2>${customer.reservations.size()}</h2><p>Lượt đặt phòng</p><span class="summary-icon second">⌂</span><h2>${customer.stays.size()}</h2><p>Lịch sử lưu trú</p></section></div>
    <section class="panel table-panel"><div class="panel-title"><div><h2>Lịch sử đặt phòng</h2><p>Các reservation mới nhất của khách hàng</p></div></div><c:choose><c:when test="${empty customer.reservations}"><div class="empty-state compact"><span>▤</span><p>Chưa có lịch sử đặt phòng.</p></div></c:when><c:otherwise><div class="table-wrap"><table><thead><tr><th>Mã booking</th><th>Ngày lưu trú</th><th>Trạng thái</th><th>Khách</th><th>Tổng tiền</th><th>Ngày đặt</th></tr></thead><tbody><c:forEach items="${customer.reservations}" var="x"><tr><td><strong class="code"><c:out value="${x.bookingCode}"/></strong></td><td>${x.checkIn} → ${x.checkOut}</td><td><span class="status muted"><c:out value="${x.status}"/></span></td><td>${x.adults} NL / ${x.children} TE</td><td>${x.total}</td><td>${x.bookedAt}</td></tr></c:forEach></tbody></table></div></c:otherwise></c:choose></section>
    <section class="panel table-panel"><div class="panel-title"><div><h2>Lịch sử lưu trú</h2><p>Phòng đã và đang được phân bổ</p></div></div><c:choose><c:when test="${empty customer.stays}"><div class="empty-state compact"><span>⌂</span><p>Chưa có lịch sử lưu trú.</p></div></c:when><c:otherwise><div class="table-wrap"><table><thead><tr><th>Booking</th><th>Lưu trú thực tế</th><th>Phòng</th><th>Loại phòng</th><th>Phân phòng</th><th>Hiện tại</th></tr></thead><tbody><c:forEach items="${customer.stays}" var="x"><tr><td><c:out value="${x.bookingCode}"/></td><td>${x.actualCheckIn} → ${x.actualCheckOut}</td><td><c:out value="${x.roomNumber}"/></td><td><c:out value="${x.roomType}"/></td><td>${x.assignedAt} → ${x.unassignedAt}</td><td>${x.current?'Có':'Không'}</td></tr></c:forEach></tbody></table></div></c:otherwise></c:choose></section>
</div></main></div></body></html>
