<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="activePage" value="${mode=='create'?'create':'customers'}"/><c:set var="moduleCode" value="${mode=='create'?'UC26':'UC27'}"/><c:set var="pageTitle" value="${mode=='create'?'Tạo khách walk-in':'Cập nhật khách hàng'}"/>
<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${pageTitle} — LuxeStay HMS</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/receptionist.css?v=20260819"></head><body><div class="app-shell">
<%@ include file="../fragments/sidebar.jspf" %><main class="main-panel"><%@ include file="../fragments/header.jspf" %><div class="content narrow-content">
    <a class="back-link" href="${pageContext.request.contextPath}/receptionist/customers">← Quay lại danh sách</a>
    <div class="page-heading"><div><p class="eyebrow">${moduleCode} • CUSTOMER PROFILE</p><h1>${pageTitle}</h1><p>${mode=='create'?'Đăng ký hồ sơ khách đến trực tiếp tại quầy lễ tân.':'Chỉnh sửa thông tin liên hệ và giấy tờ khách hàng.'}</p></div></div>
    <section class="panel form-panel"><c:if test="${not empty errors.general}"><p class="alert error"><c:out value="${errors.general}"/></p></c:if>
    <form method="post" action="${pageContext.request.contextPath}/receptionist/customers/${mode=='create'?'create':'update'}"><c:if test="${mode=='edit'}"><input type="hidden" name="id" value="${customer.id}"><input type="hidden" name="version" value="${customer.version}"></c:if>
      <div class="section-label"><span>01</span><div><strong>Thông tin cơ bản</strong><small>Các trường có dấu * là bắt buộc.</small></div></div>
      <div class="form-grid"><label>Họ và tên *<input name="fullName" maxlength="150" required value="<c:out value='${customer.fullName}'/>" placeholder="Nguyễn Văn A"><small class="field-error"><c:out value="${errors.fullName}"/></small></label><label>Email<input type="email" name="email" maxlength="255" value="<c:out value='${customer.email}'/>" placeholder="name@example.com"><small class="field-error"><c:out value="${errors.email}"/></small></label><label>Số điện thoại<input name="phone" maxlength="30" value="<c:out value='${customer.phone}'/>" placeholder="09xxxxxxxx"><small class="field-error"><c:out value="${errors.phone}"/></small></label><label>Ngày sinh<input type="date" name="dateOfBirth" value="${customer.dateOfBirth}"><small class="field-error"><c:out value="${errors.dateOfBirth}"/></small></label></div>
      <div class="section-label"><span>02</span><div><strong>Giấy tờ & liên hệ</strong><small>Loại và số giấy tờ phải được nhập cùng nhau.</small></div></div>
      <div class="form-grid"><label>Loại giấy tờ<input name="idDocumentType" maxlength="30" value="<c:out value='${customer.idDocumentType}'/>" placeholder="CCCD / PASSPORT"><small class="field-error"><c:out value="${errors.idDocumentType}"/></small></label><label>Số giấy tờ<input name="idDocumentNumber" maxlength="50" value="<c:out value='${customer.idDocumentNumber}'/>" placeholder="Nhập số giấy tờ"><small class="field-error"><c:out value="${errors.idDocumentNumber}"/></small></label><label>Quốc tịch<input name="nationality" maxlength="80" value="<c:out value='${customer.nationality}'/>" placeholder="Việt Nam"><small class="field-error"><c:out value="${errors.nationality}"/></small></label><label>Địa chỉ<input name="address" maxlength="255" value="<c:out value='${customer.address}'/>" placeholder="Địa chỉ liên hệ"><small class="field-error"><c:out value="${errors.address}"/></small></label></div>
      <div class="form-actions"><a class="secondary-button" href="${pageContext.request.contextPath}/receptionist/customers">Hủy bỏ</a><button class="primary" type="submit">✓ Lưu thông tin</button></div>
    </form></section>
</div></main></div></body></html>
