<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="activePage" value="customers"/><c:set var="moduleCode" value="UC24"/><c:set var="pageTitle" value="Tra cứu & Quản lý khách hàng"/>
<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Khách hàng — Grand Horizon</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/receptionist.css?v=20260814"></head><body><div class="app-shell">
<%@ include file="../fragments/sidebar.jspf" %><main class="main-panel"><%@ include file="../fragments/header.jspf" %><div class="content">
    <div class="page-heading"><div><p class="eyebrow">UC24 • CUSTOMER DIRECTORY</p><h1>Danh sách khách hàng</h1><p>Tìm kiếm theo tên, số điện thoại, email, giấy tờ hoặc mã khách hàng.</p></div><a class="primary" href="${pageContext.request.contextPath}/receptionist/customers/create">＋ Tạo khách walk-in</a></div>
    <section class="panel search-panel"><form class="filters" method="get"><label class="grow">Từ khóa<input name="keyword" value="<c:out value='${criteria.keyword}'/>" placeholder="Tên, điện thoại, email, CCCD/Hộ chiếu..."></label><label>Trạng thái<select name="status"><option value="">Tất cả</option><option value="ACTIVE" ${criteria.status=='ACTIVE'?'selected':''}>Hoạt động</option><option value="INACTIVE" ${criteria.status=='INACTIVE'?'selected':''}>Ngừng hoạt động</option></select></label><button class="primary" type="submit">⌕ Tìm kiếm</button></form></section>
    <section class="panel table-panel"><div class="panel-title"><div><h2>Kết quả tra cứu</h2><p>${result.totalItems} khách hàng được tìm thấy</p></div><span class="count-badge">Trang ${result.page}/${result.totalPages()}</span></div>
    <c:choose><c:when test="${empty result.items}"><div class="empty-state"><span>⌕</span><h3>Không tìm thấy khách hàng</h3><p>Hãy thử một từ khóa hoặc trạng thái khác.</p></div></c:when><c:otherwise><div class="table-wrap"><table><thead><tr><th>Mã KH</th><th>Họ và tên</th><th>Điện thoại</th><th>Email</th><th>Giấy tờ</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><c:forEach items="${result.items}" var="x"><tr><td><strong class="code"><c:out value="${x.code}"/></strong></td><td><strong><c:out value="${x.fullName}"/></strong></td><td><c:out value="${x.phone}"/></td><td><c:out value="${x.email}"/></td><td><c:out value="${x.idNumber}"/></td><td><span class="status ${x.status=='ACTIVE'?'success':'muted'}"><c:out value="${x.status}"/></span></td><td><a class="table-link" href="${pageContext.request.contextPath}/receptionist/customers/view?id=${x.id}">Xem</a><a class="table-link" href="${pageContext.request.contextPath}/receptionist/customers/edit?id=${x.id}">Sửa</a></td></tr></c:forEach></tbody></table></div><nav class="pagination"><c:if test="${result.page>1}"><a href="?keyword=${criteria.keyword}&status=${criteria.status}&page=${result.page-1}">← Trước</a></c:if><span>Trang ${result.page} / ${result.totalPages()}</span><c:if test="${result.page<result.totalPages()}"><a href="?keyword=${criteria.keyword}&status=${criteria.status}&page=${result.page+1}">Sau →</a></c:if></nav></c:otherwise></c:choose></section>
</div></main></div></body></html>
