<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="activePage" value="customers"/><c:set var="moduleCode" value="UC24"/><c:set var="pageTitle" value="Quản lý khách hàng"/>
<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quản lý khách hàng — LuxeStay HMS</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/receptionist.css?v=20260819"></head><body><div class="app-shell">
<%@ include file="../fragments/sidebar.jspf" %><main class="main-panel"><%@ include file="../fragments/header.jspf" %><div class="content">
    <div class="page-heading"><div><h1>Quản lý khách hàng</h1><p>Tìm kiếm, xem và cập nhật hồ sơ cùng lịch sử lưu trú của khách.</p></div><div class="page-actions"><a class="secondary-button" href="#search"><span class="material-symbols-outlined">filter_list</span>Bộ lọc</a><a class="primary" href="${pageContext.request.contextPath}/receptionist/customers/create"><span class="material-symbols-outlined">person_add</span>Tạo hồ sơ</a></div></div>
    <section class="panel search-panel" id="search"><form class="filters" method="get"><label class="grow">Tìm khách hàng<input name="keyword" value="<c:out value='${criteria.keyword}'/>" placeholder="Tên, điện thoại, email hoặc mã hồ sơ..."></label><label>Trạng thái<select name="status"><option value="">Tất cả</option><option value="ACTIVE" ${criteria.status=='ACTIVE'?'selected':''}>Hoạt động</option><option value="INACTIVE" ${criteria.status=='INACTIVE'?'selected':''}>Ngừng hoạt động</option></select></label><button class="primary" type="submit"><span class="material-symbols-outlined">search</span>Tìm kiếm</button></form></section>
    <section class="panel table-panel"><div class="panel-title"><div><h2>Guest Directory</h2><p>Hiển thị ${result.items.size()} trong tổng số ${result.totalItems} hồ sơ</p></div><span class="count-badge">Trang ${result.page}/${result.totalPages()}</span></div>
    <c:choose><c:when test="${empty result.items}"><div class="empty-state"><span class="material-symbols-outlined">person_search</span><h3>Không tìm thấy khách hàng</h3><p>Hãy thử từ khóa hoặc trạng thái khác.</p></div></c:when><c:otherwise><div class="table-wrap"><table><thead><tr><th>Khách hàng</th><th>Liên hệ</th><th>Giấy tờ</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><c:forEach items="${result.items}" var="x"><tr><td><div class="guest-cell"><span class="guest-avatar">${x.fullName.substring(0,1)}</span><div><strong><c:out value="${x.fullName}"/></strong><small>ID: <c:out value="${x.code}"/></small></div></div></td><td class="contact-cell"><c:out value="${x.phone}"/><small><c:out value="${x.email}"/></small></td><td><c:out value="${x.idNumber}"/></td><td><span class="status ${x.status=='ACTIVE'?'success':'muted'}"><c:out value="${x.status}"/></span></td><td><a class="table-link" href="${pageContext.request.contextPath}/receptionist/customers/view?id=${x.id}">Xem hồ sơ</a><a class="table-link" href="${pageContext.request.contextPath}/receptionist/customers/edit?id=${x.id}">Sửa</a></td></tr></c:forEach></tbody></table></div><nav class="pagination"><c:if test="${result.page>1}"><a href="?keyword=${criteria.keyword}&status=${criteria.status}&page=${result.page-1}">‹ Trước</a></c:if><span>Trang ${result.page} / ${result.totalPages()}</span><c:if test="${result.page<result.totalPages()}"><a href="?keyword=${criteria.keyword}&status=${criteria.status}&page=${result.page+1}">Sau ›</a></c:if></nav></c:otherwise></c:choose></section>
</div></main></div></body></html>
