<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="activePage" value="rooms"/><c:set var="moduleCode" value="UC29"/><c:set var="pageTitle" value="Tra cứu phòng trống"/>
<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phòng trống — Grand Horizon</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/receptionist.css?v=20260814"></head><body><div class="app-shell">
<%@ include file="../fragments/sidebar.jspf" %><main class="main-panel"><%@ include file="../fragments/header.jspf" %><div class="content">
    <div class="page-heading"><div><p class="eyebrow">UC29 • ROOM AVAILABILITY</p><h1>Phòng sẵn sàng phục vụ</h1><p>Kiểm tra phòng phù hợp theo yêu cầu và khoảng ngày của reservation.</p></div></div>
    <section class="panel search-panel"><form class="filters" method="get"><label class="grow">Reservation room ID<input type="number" min="1" name="reservationRoomId" value="${reservationRoomId}" required placeholder="Ví dụ: 1"></label><label>Tầng (tùy chọn)<input type="number" name="floor" value="${floor}" placeholder="Tất cả tầng"></label><button class="primary" type="submit">⌕ Kiểm tra phòng</button></form><c:if test="${not empty lookupError}"><p class="alert error"><c:out value="${lookupError}"/></p></c:if></section>
    <section class="panel table-panel"><div class="panel-title"><div><h2>Kết quả phòng trống</h2><p><c:choose><c:when test="${not empty rooms}">Ngày yêu cầu: ${rooms[0].checkIn} → ${rooms[0].checkOut}</c:when><c:otherwise>Nhập Reservation room ID để bắt đầu tra cứu.</c:otherwise></c:choose></p></div><c:if test="${not empty rooms}"><span class="count-badge">${rooms.size()} phòng</span></c:if></div>
    <c:choose><c:when test="${empty rooms}"><div class="empty-state"><span>▦</span><h3>Chưa có kết quả hiển thị</h3><p>Hệ thống sẽ loại phòng bẩn, bảo trì hoặc đã trùng lịch.</p></div></c:when><c:otherwise><div class="room-grid"><c:forEach items="${rooms}" var="x"><article class="room-card"><div class="room-number"><span>⌂</span><div><small>ROOM</small><strong><c:out value="${x.roomNumber}"/></strong></div></div><span class="status success">SẴN SÀNG</span><dl><dt>Tầng</dt><dd>${x.floor}</dd><dt>Loại phòng</dt><dd><c:out value="${x.typeCode}"/> — <c:out value="${x.typeName}"/></dd><dt>Loại giường</dt><dd><c:out value="${x.bedType}"/></dd><dt>Sức chứa</dt><dd>${x.maxAdults} người lớn · ${x.maxChildren} trẻ em</dd><dt>Vệ sinh</dt><dd><c:out value="${x.cleaningStatus}"/></dd></dl></article></c:forEach></div></c:otherwise></c:choose></section>
</div></main></div></body></html>
